// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IHandler is an autogenerated mock type for the IHandler type
type IHandler struct {
	mock.Mock
}

// AddCashFlow provides a mock function with given fields: c
func (_m *IHandler) AddCashFlow(c *gin.Context) {
	_m.Called(c)
}

// DeleteCashFlow provides a mock function with given fields: c
func (_m *IHandler) DeleteCashFlow(c *gin.Context) {
	_m.Called(c)
}

// GetCashFlow provides a mock function with given fields: c
func (_m *IHandler) GetCashFlow(c *gin.Context) {
	_m.Called(c)
}

// GetCashFlows provides a mock function with given fields: ctx
func (_m *IHandler) GetCashFlows(ctx *gin.Context) {
	_m.Called(ctx)
}

// UpdateCashFlows provides a mock function with given fields: c
func (_m *IHandler) UpdateCashFlow(c *gin.Context) {
	_m.Called(c)
}
